### ISSUE TITLE
image not displaying

### ISSUE THREAD

**Issue by wrwalker12** [wrwalker12/highly-original-oertextbook#1]
I inserted an image file (list.jpg) in my planning chapter ([020-planning.md](https://github.com/wrwalker12/cooking-textbook/blob/main/text/020-planning.md). It's displaying in my repository but not on the GH pages site: https://wrwalker12.github.io/cooking-textbook/020-planning.html

Not sure what I'm missing?

**Comment by chrisdaaz** [comment]
@wrwalker12 thanks for tagging me! 

I think it's a problem with the path. The first slash transforms the `src` attribute for the image to `https://wrwalker12.github.io/images/list.jpg` but removing the slash will make it into a relative path: `https://wrwalker12.github.io/cooking-textbook/images/list.jpg`

try this:
```
![Sample shopping list](images/list.jpg)
```

**Comment by wrwalker12** [comment]
I tried removing that slash, but then it looks like it's looking for an image folder inside the text folder, so it didn't work.

**Comment by wrwalker12** [comment]
It's odd, but when I remove the slash, the url becomes 

https://github.com/wrwalker12/cooking-textbook/blob/main/text/images/list.jpg

**Comment by wrwalker12** [comment]
Wait, ok, so it doesn't look like it's working in the .md file, but when I go to the site, it is displaying. OK, so removing that slash worked. Thanks!
