### ISSUE TITLE
image instructions

### ISSUE THREAD

**Issue by wrwalker12** [wrwalker12/highly-original-oertextbook#2]
FYI, when I initially inserted the image info, I used the syntax from your documentation

This didn't work. I looked up the markdown guide that you referenced in the documentation and realized that I needed to add the images folder info (/images/filename.jpg) before the filename.

Letting you know in case you want to update your documentation.

**Comment by chrisdaaz** [comment]
thanks, i appreciate it! just updated the docs:

https://github.com/nulib-oer/lantern/wiki/06-Images-and-Media
